In [2]:
import pandas as pd
import numpy as np

In [4]:
data2020=pd.read_csv('2020data.csv')
data2023=pd.read_csv('2023data.csv')

In [5]:
data2023

,addref,city,assembly,body,make,model,year,engine,transmission,fuel,color,registered,mileage,price
0,7943732,Peshawar,NaN,Sedan,Toyota,Corolla,2013.0,1300.0,Manual,Petrol,Silver Metallic,Lahore,145000,2870000.0
1,7730314,Lahore,NaN,Sedan,Honda,City,2000.0,1300.0,Manual,Petrol,Blue,Lahore,230000,995000.0
2,7943737,Lahore,NaN,Sedan,Toyota,Yaris,2021.0,1300.0,Manual,Petrol,Super White,Punjab,60500,3585000.0
3,7943733,Lahore,NaN,Hatchback,Suzuki,Swift,2017.0,1300.0,Manual,Petrol,Grey,Islamabad,87000,2250000.0
4,7923484,Lahore,NaN,Sedan,Honda,Civic,2017.0,1800.0,Automatic,Petrol,Grey,Lahore,86000,4850000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77873,7775164,Daska,NaN,Sedan,Honda,Civic,2019.0,1800.0,Automatic,Petrol,Taffeta White,Islamabad,58000,5590000.0
77874,7772775,Abbottabad,Imported,Hatchback,Suzuki,Alto,2015.0,660.0,Automatic,Petrol,Brown,Islamabad,65000,2420000.0
77875,7773716,Faisalabad,Imported,Crossover,MG,HS,2021.0,1490.0,Automatic,Petrol,Arctic White,Un-Registered,5000,7500000.0
77876,7322377,Quetta,NaN,Sedan,Suzuki,Baleno,2005.0,1300.0,Manual,Petrol,Silver,Lahore,19000,1250000.0
77877,7770898,Mandi,Imported,Sedan,Toyota,Corolla,1998.0,1600.0,Automatic,Petrol,Black,Lahore,12345,1150000.0

In [6]:
#cleaning 2023 Dataset
data2023.drop(['addref','color','city','registered','fuel','make','body'],axis=1,errors='ignore',inplace=True)
data2023['transmission'] = data2023['transmission'].map({'Automatic': 1, 'Manual': 0})
data2023

       assembly    model    year  engine  transmission  mileage      price
0           NaN  Corolla  2013.0  1300.0             0   145000  2870000.0
1           NaN     City  2000.0  1300.0             0   230000   995000.0
2           NaN    Yaris  2021.0  1300.0             0    60500  3585000.0
3           NaN    Swift  2017.0  1300.0             0    87000  2250000.0
4           NaN    Civic  2017.0  1800.0             1    86000  4850000.0
...         ...      ...     ...     ...           ...      ...        ...
77873       NaN    Civic  2019.0  1800.0             1    58000  5590000.0
77874  Imported     Alto  2015.0   660.0             1    65000  2420000.0
77875  Imported       HS  2021.0  1490.0             1     5000  7500000.0
77876       NaN   Baleno  2005.0  1300.0             0    19000  1250000.0
77877  Imported  Corolla  1998.0  1600.0             1    12345  1150000.0

[77878 rows x 7 columns]

In [7]:
data2023['assembly'].fillna("local", inplace=True)
data2023['assembly'] = data2023['assembly'].map({'Imported': 1, 'local': 0})
data2023

C:\Users\HP\AppData\Local\Temp\ipykernel_29092\1580519628.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data2023['assembly'].fillna("local", inplace=True)

       assembly    model    year  engine  transmission  mileage      price
0           NaN  Corolla  2013.0  1300.0             0   145000  2870000.0
1           NaN     City  2000.0  1300.0             0   230000   995000.0
2           NaN    Yaris  2021.0  1300.0             0    60500  3585000.0
3           NaN    Swift  2017.0  1300.0             0    87000  2250000.0
4           NaN    Civic  2017.0  1800.0             1    86000  4850000.0
...         ...      ...     ...     ...           ...      ...        ...
77873       NaN    Civic  2019.0  1800.0             1    58000  5590000.0
77874       1.0     Alto  2015.0   660.0             1    65000  2420000.0
77875       1.0       HS  2021.0  1490.0             1     5000  7500000.0
77876       NaN   Baleno  2005.0  1300.0             0    19000  1250000.0
77877       1.0  Corolla  1998.0  1600.0             1    12345  1150000.0

[77878 rows x 7 columns]

In [8]:
data2023["model"].value_counts().head(5)

model
Corolla    12871
Civic       8275
City        5277
Mehran      4588
Cultus      4463
Name: count, dtype: int64

In [9]:
corolla_df = data2023[data2023['model'] == 'Corolla']
civic_df = data2023[data2023['model'] == 'Civic']
city_df = data2023[data2023['model'] == 'City']
mehran_df = data2023[data2023['model'] == 'Mehran']
cultus_df = data2023[data2023['model'] == 'Cultus']
cultus_df

       assembly   model    year  engine  transmission  mileage      price
18          NaN  Cultus  2019.0  1000.0             0    96200  2950000.0
22          NaN  Cultus  2017.0  1000.0             0    52500  2505000.0
110         NaN  Cultus  2017.0  1000.0             0    39807  1695000.0
114         NaN  Cultus  2018.0  1000.0             1    65000  2870000.0
138         NaN  Cultus  2018.0  1000.0             1    72000  3100000.0
...         ...     ...     ...     ...           ...      ...        ...
77796       NaN  Cultus  2015.0  1000.0             0    76357  1470000.0
77809       NaN  Cultus  2015.0  1000.0             0    79000  1400000.0
77830       NaN  Cultus  2008.0  1000.0             0    60800   990000.0
77842       NaN  Cultus  2007.0  1000.0             0   100000   725000.0
77867       NaN  Cultus  2002.0  1000.0             0       15   820000.0

[4463 rows x 7 columns]